FROM python:3.11

RUN pip install --upgrade pip setuptools wheel

COPY ./requirements.txt /requirements.txt
RUN pip install -r /requirements.txt

COPY ./manage.py /manage.py
COPY ./run_asgi.py /run_asgi.py
COPY ./docker-entrypoint /docker-entrypoint
COPY ./dotenv /dotenv

RUN mkdir /logs

COPY ./backend /backend
COPY ./config /config
