services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant:/data

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: local_test_root
      POSTGRES_PASSWORD: cfhgvjbknlm
      POSTGRES_DB: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
