# Generated by Django 4.2.16 on 2024-11-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0002_conversation_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="state",
            field=models.CharField(
                choices=[("PENDING", "Pending"), ("COMPLETE", "Complete")], default="COMPLETE", max_length=10
            ),
        ),
    ]
