# Generated by Django 4.2.16 on 2024-11-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0004_message_chatbot_mes_convers_a0cf0e_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="assistant_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
