# Generated by Django 4.2.11 on 2024-09-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_login_ip",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="last_login_time",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
